ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views
from . import views

app_name = "shop"

urlpatterns = [ 

    path('', views.acceuil, name='accueil'),
    path('boutique/', views.shop, name='shop'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('plats/', views.plats, name='plats'),
    


    path('panier/', views.panier, name='panier'),
    path('commande/', views.commande, name='commande'),
    path('update_article/', views.update_article, name='update_article'),
    path('traitement-commande/', views.traitementCommande, name="traitement_commande"),
    
    # Chatbot
    path('chatbot/', views.chatbot, name='chatbot'),
    
    # Langue et devise
    path('change_language/', views.change_language, name='change_language'),
    path('change_currency/', views.change_currency, name='change_currency'),
    path('get_currency_info/', views.get_currency_info, name='get_currency_info'),
    
    # Aide
    path('aide/', views.aide, name='aide'),
    path('aide/commande/', views.aide_commande, name='aide_commande'),
    path('aide/livraison/', views.aide_livraison, name='aide_livraison'),
    path('aide/paiement/', views.aide_paiement, name='aide_paiement'),
    path('aide/compte/', views.aide_compte, name='aide_compte'),
    path('aide/retours/', views.aide_retours, name='aide_retours'),
    path('produit/<int:myid>/', views.details_produit, name='detail'),
    
    # Favoris
    path('favoris/', views.favoris_page, name='favoris'),
    path('toggle_favoris/', views.toggle_favoris, name='toggle_favoris'),


    path('register', views.register, name='register'),
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('settings/', views.user_settings, name='settings'),
    
    path('password-reset/<str:uidb64>/<str:token>', views.activate_account_view, name='password_reset'),
    path("password_reset_view/", views.password_reset_request, name='password_reset_view'),
    path("password_reset_done/", views.password_reset_done, name='password_reset_done'),
    path("password_reset_confirm/<str:uidb64>/<str:token>/<str:email>/", views.password_reset_confirm, name='password_reset_confirm'),
    path("password_reset_complete/", views.password_reset_complete, name='password_reset_complete'),


    
]

templates/navbar.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>

   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>Tradi</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">

   <!-- style css -->
   <link rel="stylesheet" type="text/css" href="{% static 'css/new/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{% static 'css/new/responsive.css' %}">
   <!-- fevicon -->
   <!-- <link rel="icon" href="images/fevicon.png" type="image/gif" /> - icône supprimée -->
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{% static 'css/new/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <!-- fonts -->
   <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet">
   <!-- font awesome -->
   <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
   <!--  -->
   <!-- owl stylesheets -->
   <link href="https://fonts.googleapis.com/css?family=Great+Vibes|Poppins:400,700&display=swap&subset=latin-ext" rel="stylesheet">
   <link rel="stylesheet" href="{% static 'css/new/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/new/owl.theme.default.min.css' %}">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">



    <!-- Test -->
    <!-- Test -->
    <!-- Test -->
    <!-- Test -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
     integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

     <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" 
     integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

     <link rel="stylesheet"
     href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"> -->
    <script src="https://cdn.cinetpay.com/seamless/main.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <!--Bootsrap-->
    
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Popper.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>


    <!-- google-font -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    
    <!-- google-font -->

    <script defer type="text/javascript">

      user = '{{ request.user }}'

      function getToken(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie != '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = jQuery.trim(cookies[i]);
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) == (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }
      var csrftoken = getToken('csrftoken');


      function getCookie(name){
        var cookieArr = document.cookie.split(";");

        // Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++) {
          var cookiePair = cookieArr[i].split("=");

          /* Removing whitespace at the beginning of the cookie name
          and compare i with the given string */
          if(name==cookiePair[0].trim()){
            // Decode the cookie value and return
            return decodeURIComponent(cookiePair[1]);
          }
        }

        // Return null if not found
        return null;
      }

      var panier = JSON.parse(getCookie('panier'));

      if( panier == undefined){
        panier = {};
        console.log("panier cree");
        document.cookie = "panier=" + JSON.stringify(panier) + ";domain=;path=/";
      }

      console.log('panier', panier);

  
    </script>

  </head>
  <body>

  <!-- site en contruction  -->
   
   <div class="container">
   
    {% block auth %}
    
    {% endblock auth %}


   </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    
    <script type="text/javascript" src="{% static 'js/navbar.js' %}"></script>

     <!-- Javascript files-->
     <!-- Javascript files-->
     <!-- Javascript files-->
     <!-- Javascript files-->
     <script src="{% static 'js/new/jquery.min.js' %}"></script>
     <script src="{% static 'js/new/popper.min.js' %}"></script>
     <script src="{% static 'js/new/bootstrap.bundle.min.js' %}"></script>
     <script src="{% static 'js/new/jquery-3.0.0.min.js' %}"></script>
     <script src="{% static 'js/new/plugin.js' %}"></script>
     <!-- sidebar -->
     <script src="{% static 'js/new/jquery.mCustomScrollbar.concat.min.js' %}"></script>
     <script src="{% static 'js/new/custom.js' %}"></script>
     <script>
        function openNav() {
          document.getElementById("mySidenav").style.width = "250px";
        }
        
        function closeNav() {
          document.getElementById("mySidenav").style.width = "0";
        }
     </script>

     <!-- Javascript files-->
     <!-- Javascript files-->
     <!-- Javascript files-->
    
   


  </body>
</html>

templates/password_reset.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Mot de passe oublié - Tradishop</title>
  <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>

<body>
  <main class="container">
    <section class="left">
      <div class="content">
        <h1>Mot de passe oublié ?</h1>
        <p>
          Pas de panique ! Entrez votre adresse email et nous vous enverrons un lien 
          pour réinitialiser votre mot de passe en toute sécurité.
        </p>
        <div class="features">
          <div class="feature">
            <i class="fas fa-shield-alt"></i>
            <span>Processus sécurisé</span>
          </div>
          <div class="feature">
            <i class="fas fa-clock"></i>
            <span>Lien valide 24h</span>
          </div>
          <div class="feature">
            <i class="fas fa-envelope"></i>
            <span>Email instantané</span>
          </div>
        </div>
      </div>
    </section>
    
    <section class="right">
      <div class="form-container">
        <div class="form-header">
          <h2>Réinitialiser le mot de passe</h2>
          <p>Entrez votre adresse email pour recevoir le lien de réinitialisation</p>
        </div>

        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <i class="fas fa-{% if message.tags == 'error' %}exclamation-triangle{% else %}check-circle{% endif %}"></i>
            <span>{{ message|safe }}</span>
            <button type="button" class="close" onclick="this.parentElement.style.display='none'">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}

        <form method="POST" id="resetForm" novalidate>
          {% csrf_token %}
          
          <div class="form-group">
            <div class="input-group">
              <i class="fas fa-envelope"></i>
              <input class="text email" type="email" name="email" placeholder="Votre adresse email" required 
                     autocomplete="email">
            </div>
            <small class="help-text">Entrez l'adresse email associée à votre compte</small>
          </div>

          <button type="submit" class="submit-btn">
            <i class="fas fa-paper-plane"></i>
            Envoyer le lien de réinitialisation
          </button>
        </form>

        <div class="form-footer">
          <p>Vous vous souvenez de votre mot de passe ? <a href="{% url 'shop:login' %}" class="login-link">Se connecter</a></p>
          <p>Pas encore de compte ? <a href="{% url 'shop:register' %}" class="register-link">S'inscrire</a></p>
        </div>
      </div>
    </section>
  </main>

  <script>
    // Form validation
    document.getElementById('resetForm').addEventListener('submit', function(e) {
      const email = document.querySelector('input[name="email"]').value.trim();
      
      if (!email) {
        e.preventDefault();
        alert('Veuillez entrer votre adresse email');
        return false;
      }
      
      // Validation email basique
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        e.preventDefault();
        alert('Veuillez entrer une adresse email valide');
        return false;
      }
    });

    // Auto-focus on email field
    document.addEventListener('DOMContentLoaded', function() {
      const emailField = document.querySelector('input[name="email"]');
      if (emailField) {
        emailField.focus();
      }
    });

    // Real-time validation feedback
    document.querySelector('input[name="email"]').addEventListener('blur', function() {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (this.value.trim() && emailRegex.test(this.value)) {
        this.classList.add('valid');
        this.classList.remove('invalid');
      } else if (this.value.trim()) {
        this.classList.add('invalid');
        this.classList.remove('valid');
      } else {
        this.classList.remove('valid', 'invalid');
      }
    });
  </script>
</body>
</html>

templates/password_reset_complete.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Mot de passe réinitialisé - Tradishop</title>
  <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>

<body>
  <main class="container">
    <section class="center">
      <div class="success-container">
        <div class="success-icon">
          <i class="fas fa-check-circle"></i>
        </div>
        <h1>Mot de passe réinitialisé !</h1>
        <p class="success-message">
          Votre mot de passe a été réinitialisé avec succès. 
          Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.
        </p>
        
        <div class="info-box">
          <h3><i class="fas fa-info-circle"></i> Prochaines étapes :</h3>
          <ul>
            <li>Connectez-vous avec votre nouveau mot de passe</li>
            <li>Vérifiez que tout fonctionne correctement</li>
            <li>Conservez votre mot de passe en lieu sûr</li>
            <li>Contactez-nous si vous rencontrez des problèmes</li>
          </ul>
        </div>

        <div class="action-buttons">
          <a href="{% url 'shop:login' %}" class="btn btn-primary">
            <i class="fas fa-sign-in-alt"></i>
            Se connecter maintenant
          </a>
          <a href="{% url 'shop:accueil' %}" class="btn btn-secondary">
            <i class="fas fa-home"></i>
            Retour à l'accueil
          </a>
        </div>
      </div>
    </section>
  </main>

  <script>
    // Auto-redirect vers la connexion après 5 secondes
    setTimeout(function() {
      window.location.href = '{% url "shop:login" %}';
    }, 5000);

    // Afficher un compte à rebours
    let countdown = 5;
    const countdownElement = document.createElement('div');
    countdownElement.className = 'countdown';
    countdownElement.innerHTML = `Redirection automatique dans <span id="countdown-number">${countdown}</span> secondes...`;
    document.querySelector('.success-container').appendChild(countdownElement);

    const countdownInterval = setInterval(function() {
      countdown--;
      document.getElementById('countdown-number').textContent = countdown;
      if (countdown <= 0) {
        clearInterval(countdownInterval);
      }
    }, 1000);
  </script>
</body>
</html>

templates/password_reset_confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Nouveau mot de passe - Tradishop</title>
  <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>

<body>
  <main class="container">
    <section class="left">
      <div class="content">
        <h1>Nouveau mot de passe</h1>
        <p>
          Créez un nouveau mot de passe sécurisé pour votre compte Tradishop. 
          Assurez-vous qu'il soit suffisamment fort pour protéger vos données.
        </p>
        <div class="features">
          <div class="feature">
            <i class="fas fa-lock"></i>
            <span>Mot de passe sécurisé</span>
          </div>
          <div class="feature">
            <i class="fas fa-shield-alt"></i>
            <span>Protection des données</span>
          </div>
          <div class="feature">
            <i class="fas fa-check-circle"></i>
            <span>Validation en temps réel</span>
          </div>
        </div>
      </div>
    </section>
    
    <section class="right">
      <div class="form-container">
        <div class="form-header">
          <h2>Créer un nouveau mot de passe</h2>
          <p>Entrez votre nouveau mot de passe ci-dessous</p>
        </div>

        {% for message in messages %}
          <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <i class="fas fa-{% if message.tags == 'error' %}exclamation-triangle{% else %}check-circle{% endif %}"></i>
            <span>{{ message|safe }}</span>
            <button type="button" class="close" onclick="this.parentElement.style.display='none'">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}

        <form method="POST" id="resetConfirmForm" novalidate>
          {% csrf_token %}
          
          <div class="form-group">
            <div class="input-group">
              <i class="fas fa-lock"></i>
              <input class="text" type="password" name="password" id="password" placeholder="Nouveau mot de passe" required 
                     minlength="8" pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]"
                     title="Le mot de passe doit contenir au moins 8 caractères, une majuscule, une minuscule, un chiffre et un caractère spécial">
              <i class="fas fa-eye toggle-password" onclick="togglePassword('password')"></i>
            </div>
            <small class="help-text">Minimum 8 caractères avec majuscule, minuscule, chiffre et caractère spécial</small>
            <div id="password-strength" class="password-strength"></div>
          </div>

          <div class="form-group">
            <div class="input-group">
              <i class="fas fa-lock"></i>
              <input class="text w3lpass" type="password" name="repassword" id="repassword" placeholder="Confirmez le nouveau mot de passe" required>
              <i class="fas fa-eye toggle-password" onclick="togglePassword('repassword')"></i>
            </div>
            <div id="password-match" class="password-match"></div>
          </div>

          <button type="submit" class="submit-btn">
            <i class="fas fa-save"></i>
            Réinitialiser le mot de passe
          </button>
        </form>

        <div class="form-footer">
          <p>Vous vous souvenez de votre mot de passe ? <a href="{% url 'shop:login' %}" class="login-link">Se connecter</a></p>
        </div>
      </div>
    </section>
  </main>

  <script>
    // Toggle password visibility
    function togglePassword(fieldId) {
      const field = document.getElementById(fieldId);
      const icon = field.nextElementSibling;
      
      if (field.type === 'password') {
        field.type = 'text';
        icon.classList.remove('fa-eye');
        icon.classList.add('fa-eye-slash');
      } else {
        field.type = 'password';
        icon.classList.remove('fa-eye-slash');
        icon.classList.add('fa-eye');
      }
    }

    // Password strength checker
    function checkPasswordStrength(password) {
      let strength = 0;
      const checks = {
        length: password.length >= 8,
        lowercase: /[a-z]/.test(password),
        uppercase: /[A-Z]/.test(password),
        number: /\d/.test(password),
        special: /[@$!%*?&]/.test(password)
      };

      strength = Object.values(checks).filter(Boolean).length;
      return { strength, checks };
    }

    // Password strength indicator
    document.getElementById('password').addEventListener('input', function() {
      const password = this.value;
      const strengthDiv = document.getElementById('password-strength');
      const { strength, checks } = checkPasswordStrength(password);
      
      if (password.length > 0) {
        let strengthText = '';
        let strengthClass = '';
        
        if (strength <= 2) {
          strengthText = 'Faible';
          strengthClass = 'weak';
        } else if (strength <= 3) {
          strengthText = 'Moyen';
          strengthClass = 'medium';
        } else if (strength <= 4) {
          strengthText = 'Fort';
          strengthClass = 'strong';
        } else {
          strengthText = 'Très fort';
          strengthClass = 'very-strong';
        }
        
        strengthDiv.innerHTML = `
          <div class="strength-bar">
            <div class="strength-fill ${strengthClass}" style="width: ${(strength/5)*100}%"></div>
          </div>
          <span class="strength-text ${strengthClass}">${strengthText}</span>
        `;
        strengthDiv.className = `password-strength ${strengthClass}`;
      } else {
        strengthDiv.innerHTML = '';
        strengthDiv.className = 'password-strength';
      }
    });

    // Password confirmation validation
    document.getElementById('repassword').addEventListener('input', function() {
      const password = document.getElementById('password').value;
      const repassword = this.value;
      const matchDiv = document.getElementById('password-match');
      
      if (repassword.length > 0) {
        if (password === repassword) {
          matchDiv.innerHTML = '<i class="fas fa-check text-success"></i> Les mots de passe correspondent';
          matchDiv.className = 'password-match success';
        } else {
          matchDiv.innerHTML = '<i class="fas fa-times text-danger"></i> Les mots de passe ne correspondent pas';
          matchDiv.className = 'password-match error';
        }
      } else {
        matchDiv.innerHTML = '';
        matchDiv.className = 'password-match';
      }
    });

    // Form validation
    document.getElementById('resetConfirmForm').addEventListener('submit', function(e) {
      const password = document.getElementById('password').value;
      const repassword = document.getElementById('repassword').value;
      
      if (password !== repassword) {
        e.preventDefault();
        alert('Les mots de passe ne correspondent pas');
        return false;
      }
      
      const { strength } = checkPasswordStrength(password);
      if (strength < 3) {
        e.preventDefault();
        alert('Le mot de passe est trop faible. Veuillez choisir un mot de passe plus fort.');
        return false;
      }
    });
  </script>
</body>
</html>

templates/password_reset_done.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Email envoyé - Tradishop</title>
  <link href="{% static 'css/register.css' %}" rel="stylesheet" type="text/css" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
</head>

<body>
  <main class="container">
    <section class="center">
      <div class="success-container">
        <div class="success-icon">
          <i class="fas fa-envelope-open"></i>
        </div>
        <h1>Email envoyé !</h1>
        <p class="success-message">
          Nous avons envoyé un lien de réinitialisation à votre adresse email. 
          Vérifiez votre boîte de réception et cliquez sur le lien pour continuer.
        </p>
        
        <div class="info-box">
          <h3><i class="fas fa-info-circle"></i> Instructions :</h3>
          <ul>
            <li>Vérifiez votre boîte de réception</li>
            <li>Regardez aussi dans vos spams/courriers indésirables</li>
            <li>Le lien est valide pendant 24 heures</li>
            <li>Cliquez sur le lien pour réinitialiser votre mot de passe</li>
          </ul>
        </div>

        <div class="action-buttons">
          <a href="{% url 'shop:login' %}" class="btn btn-primary">
            <i class="fas fa-arrow-left"></i>
            Retour à la connexion
          </a>
          <a href="{% url 'shop:password_reset_view' %}" class="btn btn-secondary">
            <i class="fas fa-redo"></i>
            Renvoyer l'email
          </a>
        </div>
      </div>
    </section>
  </main>

  <script>
    // Auto-redirect après 30 secondes
    setTimeout(function() {
      if (confirm('Voulez-vous retourner à la page de connexion ?')) {
        window.location.href = '{% url "shop:login" %}';
      }
    }, 30000);
  </script>
</body>
</html>